scheduler: queue.c ppos.c pingpong-preempcao.c
			gcc -o scheduler queue.c ppos.c pingpong-preempcao.c -Wall -I.

debug: queue.c ppos.c pingpong-preempcao.c
			gcc -o scheduler queue.c ppos.c pingpong-preempcao.c -Wall -DDEBUG -I.
