scheduler: queue.c ppos.c pingpong-scheduler.c
			gcc -o scheduler queue.c ppos.c timer.c -Wall -I.

debug: queue.c ppos.c pingpong-scheduler.c
			gcc -o scheduler queue.c ppos.c timer.c -Wall -DDEBUG -I.
